services:
  site:
    image: bt-portfolio:local
    build:
      context: .
    container_name: bt-portfolio
    volumes:
      - .:/app/
      - /app/node_modules
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
    command: "server"
